const crest = color => `data:image/svg+xml,${encodeURIComponent(
    `<svg xmlns="http://www.w3.org/2000/svg" width="40" height="40"><circle cx="20" cy="20" r="18" fill="${color}"/></svg>`,
)}`;

const teamIdentity = (id, name, teamCrest) => ({
    id,
    canonicalId: name.toLocaleLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, ''),
    provider: 'football-data',
    providerId: id,
    providerIds: {'football-data': id},
    name,
    shortName: name,
    tla: name.slice(0, 3).toUpperCase(),
    crest: teamCrest,
});

const baseMatch = ({
    id,
    status,
    utcDate,
    home,
    away,
    homeScore = null,
    awayScore = null,
    competition = 'Premier League',
    competitionId = 'PL',
    homeCrest = crest('#ef4444'),
    awayCrest = crest('#3b82f6'),
    venue = 'Scanner Stadium',
}) => ({
    id,
    utcDate,
    status,
    stage: 'REGULAR_SEASON',
    group: null,
    lastUpdated: '2026-08-03T18:30:00Z',
    sourceUpdatedAt: '2026-08-03T18:30:00Z',
        sources: ['espn'],
        broadcasts: id === 'live-secret' ? [
            {name: 'Apple TV', type: 'STREAMING', region: 'us'},
        ] : [],
        dataQuality: {missingFields: ['referees', 'aggregate']},
    homeTeam: teamIdentity(`${id}-home`, home, homeCrest),
    awayTeam: teamIdentity(`${id}-away`, away, awayCrest),
    score: {
        winner: homeScore === awayScore ? 'DRAW' : (homeScore > awayScore ? 'HOME_TEAM' : 'AWAY_TEAM'),
        duration: 'REGULAR',
        fullTime: {home: homeScore, away: awayScore},
        halfTime: {home: null, away: null},
    },
    competition: {
        id: competitionId,
        name: competition,
        code: competitionId,
        type: 'LEAGUE',
        emblem: crest('#7cff00'),
        area: {name: competition === 'Premier League' ? 'England' : 'Europe'},
    },
    season: {
        id: 'season-2026',
        startDate: '2026-08-01',
        endDate: '2027-05-30',
        currentMatchday: 4,
    },
    matchday: 4,
    venue,
    referees: [],
    enhanced_info: {
        importance_score: 80,
        source: 'ESPN',
        match_date: '2026-08-03',
        days_from_today: 0,
        tv_coverage: 'Regional',
        attendance_estimate: '45,000',
        rivalry_factor: false,
    },
});

export const fixturePayload = {
    matches: [
        baseMatch({
            id: 'live-secret',
            status: 'LIVE',
            utcDate: '2026-08-03T18:30:00Z',
            home: 'Arsenal',
            away: 'River Plate',
            homeScore: 97,
            awayScore: 96,
        }),
        baseMatch({
            id: 'finished-secret',
            status: 'FINISHED',
            utcDate: '2026-08-03T16:00:00Z',
            home: 'Wolverhampton Wanderers Women',
            away: 'Borussia Mönchengladbach Academy',
            homeScore: 95,
            awayScore: 94,
        }),
        baseMatch({
            id: 'upcoming',
            status: 'SCHEDULED',
            utcDate: '2026-08-03T23:45:00Z',
            home: 'Celtic',
            away: 'Dundee',
            competition: 'Scottish Premiership',
            competitionId: 'SPL',
        }),
        baseMatch({
            id: 'half-time',
            status: 'PAUSED',
            utcDate: '2026-08-03T17:00:00Z',
            home: 'Real Sociedad',
            away: 'Athletic Club',
            homeScore: 2,
            awayScore: 2,
            competition: 'La Liga',
            competitionId: 'PD',
        }),
        baseMatch({
            id: 'postponed',
            status: 'POSTPONED',
            utcDate: '2026-08-03T20:00:00Z',
            home: 'Ajax',
            away: 'PSV',
            competition: 'Eredivisie',
            competitionId: 'DED',
        }),
        baseMatch({
            id: 'missing-score',
            status: 'FINISHED',
            utcDate: '2026-08-03T14:00:00Z',
            home: 'Unknown Town',
            away: 'Fallback United',
            competition: 'Championship',
            competitionId: 'ELC',
            homeCrest: '/static/missing-home-crest.svg',
            awayCrest: null,
            venue: null,
        }),
        ...Array.from({length: 7}, (_, index) => baseMatch({
            id: `premier-extra-${index}`,
            status: 'SCHEDULED',
            utcDate: `2026-08-03T${String(19 + (index % 4)).padStart(2, '0')}:15:00Z`,
            home: `North London ${index + 1}`,
            away: `South Coast ${index + 1}`,
        })),
    ],
    featured_matches: [],
    total_matches: 13,
    date: '2026-08-03',
    timezone: 'America/New_York',
    source_stats: {espn_api: 12, football_data_fallback: 1, total_unique: 13},
    match_statistics: {total_matches: 13},
    last_updated: '2026-08-03T18:32:00-04:00',
    cached: true,
    stale: true,
    partial: true,
    providers: {
        espn: {
            status: 'degraded',
            successful_competitions: 4,
            failed_competitions: 1,
            successful_requests: 4,
            failed_requests: 1,
        },
        football_data: {status: 'available'},
    },
};

export const emptyFixturePayload = {
    ...fixturePayload,
    matches: [],
    total_matches: 0,
    source_stats: {espn_api: 0, football_data_fallback: 0, total_unique: 0},
    cached: false,
    stale: false,
    partial: false,
    providers: {
        espn: {
            status: 'available',
            successful_competitions: 20,
            failed_competitions: 0,
            successful_requests: 20,
            failed_requests: 0,
        },
        football_data: {status: 'not_needed'},
    },
};

export const teamPayload = {
    team_info: {
        canonicalId: 'arsenal',
        id: 'live-secret-home',
        name: 'Arsenal',
        shortName: 'Arsenal',
        tla: 'ARS',
        crest: crest('#ef4444'),
        founded: 1886,
        venue: 'Emirates Stadium',
        clubColors: 'Red / White',
        website: 'https://www.arsenal.com/',
        squad: [],
    },
    squad: [
        {id: 1, name: 'Alex Keeper', position: 'Goalkeeper', nationality: 'England', dateOfBirth: '1998-01-01'},
        {id: 2, name: 'Sam Forward', position: 'Attacker', nationality: 'England', dateOfBirth: '2000-02-02'},
    ],
    formation_data: {
        formation: '4-3-3',
        positions: {},
        count: {goalkeepers: 1, defenders: 0, midfielders: 0, attackers: 1},
    },
    recent_matches: [
        baseMatch({
            id: 'recent-secret',
            status: 'FINISHED',
            utcDate: '2026-07-28T18:00:00Z',
            home: 'Arsenal',
            away: 'Chelsea',
            homeScore: 97,
            awayScore: 96,
        }),
    ],
    upcoming_matches: [
        baseMatch({
            id: 'team-upcoming',
            status: 'SCHEDULED',
            utcDate: '2026-08-10T18:00:00Z',
            home: 'Liverpool',
            away: 'Arsenal',
        }),
    ],
    stats: {
        matches_played: 10,
        wins: 6,
        draws: 2,
        losses: 2,
        goals_for: 22,
        goals_against: 11,
        goal_difference: 11,
        form: ['W', 'D', 'W', 'L', 'W'],
        win_percentage: 60,
    },
    top_performers: {
        full_squad_by_position: {},
        young_talents: [],
        experienced_players: [],
        squad_summary: {total_players: 2, average_age: 27, youngest_player: null, oldest_player: null},
        nationality_breakdown: {England: 2},
        squad_analytics: {},
    },
    competition_analysis: {},
};
