import os


class Config:
    FOOTBALL_DATA_API_KEY = os.getenv('FOOTBALL_DATA_API_KEY')
    FOOTBALL_DATA_BASE_URL = 'https://api.football-data.org/v4'
    HTTP_CONNECT_TIMEOUT = 3.05
    HTTP_READ_TIMEOUT = 8
    PROVIDER_MAX_RETRIES = 2
    PROVIDER_MAX_JSON_BYTES = 1_000_000
    PROVIDER_RETRY_AFTER_MAX = 30
    PROVIDER_POOL_CONNECTIONS = 8
    PROVIDER_POOL_MAXSIZE = 16
    FIXTURE_CACHE_TTL = 60
    FIXTURE_STALE_TTL = 900
    FIXTURE_CACHE_MAX_ENTRIES = 64
    FIXTURE_FETCH_DEADLINE = 4
    SEND_FILE_MAX_AGE_DEFAULT = 3600
