import os


class Config:
    FOOTBALL_DATA_API_KEY = os.getenv('FOOTBALL_DATA_API_KEY')
    FOOTBALL_DATA_BASE_URL = 'https://api.football-data.org/v4'
    ESPN_BASE_URL = 'https://site.api.espn.com/apis/site/v2'
    HTTP_CONNECT_TIMEOUT = 3.05
    HTTP_READ_TIMEOUT = 8
    PROVIDER_MAX_RETRIES = 2
    PROVIDER_MAX_JSON_BYTES = 1_000_000
    PROVIDER_RETRY_AFTER_MAX = 30
    PROVIDER_POOL_CONNECTIONS = 8
    PROVIDER_POOL_MAXSIZE = 16
    REDIS_URL = os.getenv('REDIS_URL')
    REDIS_CONNECT_TIMEOUT = 1
    REDIS_READ_TIMEOUT = 1
    CACHE_NAMESPACE = 'soccer-scanner:v1'
    CACHE_MAX_KEY_LENGTH = 256
    CACHE_MAX_VALUE_BYTES = 1_000_000
    CACHE_LOCK_TTL = 15
    CACHE_LOCK_WAIT = 5
    RATE_LIMIT_MAX_REQUESTS = 60
    RATE_LIMIT_WINDOW_SECONDS = 60
    RATE_LIMIT_MAX_KEYS = 10_000
    FIXTURE_CACHE_TTL = 60
    FIXTURE_STALE_TTL = 900
    FIXTURE_CACHE_MAX_ENTRIES = 64
    FIXTURE_FETCH_DEADLINE = 4
    SEND_FILE_MAX_AGE_DEFAULT = 3600
    TRUSTED_PROXY_HOPS = int(os.getenv('TRUSTED_PROXY_HOPS', '1'))
    PUBLIC_BASE_URL = os.getenv('PUBLIC_BASE_URL', 'https://soccerscanner.pro').rstrip('/')
