import os


class Config:
    FOOTBALL_DATA_API_KEY = os.getenv('FOOTBALL_DATA_API_KEY')
    FOOTBALL_DATA_BASE_URL = 'https://api.football-data.org/v4'
    HTTP_CONNECT_TIMEOUT = 3.05
    HTTP_READ_TIMEOUT = 8
    FIXTURE_CACHE_TTL = 60
    FIXTURE_STALE_TTL = 900
    FIXTURE_CACHE_MAX_ENTRIES = 64
    FIXTURE_FETCH_DEADLINE = 4
    SEND_FILE_MAX_AGE_DEFAULT = 3600
